### ISSUE TITLE
BUG memberfactory.yml declares "customer_email" twice

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-foxy-single-sign-on#12]
```yml
---
name: foxy-memberfactory-config
---
Dynamic\Foxy\SingleSignOn\Factory\MemberFactory:
  member_mapping:
    customer_id: 'Customer_ID'
    customer_email: 'Email'
    customer_first_name: 'FirstName'
    customer_last_name: 'Surname'
    customer_email: 'Email'
    customer_password: 'Password'
    customer_password_salt: 'Salt'
    #customer_password_hash_type: 'PasswordEncryption'
```
